name: Test MinIO CLI Action

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System Info
        run: |
          echo "=== System Information ==="
          uname -a
          docker --version
          echo "=== Network Information ==="
          netstat -tuln | grep -E "(9000|9001)" || echo "Ports 9000/9001 available"

      - name: Start MinIO
        run: |
          echo "Starting MinIO..."
          # Create data directory
          sudo mkdir -p /tmp/minio-data
          sudo chmod 777 /tmp/minio-data

          # Start MinIO in background
          docker run -d \
            --name minio \
            -p 9000:9000 \
            -p 9001:9001 \
            -e "MINIO_ROOT_USER=minioadmin" \
            -e "MINIO_ROOT_PASSWORD=minioadmin" \
            -v /tmp/minio-data:/data \
            minio/minio server /data --console-address ":9001"

          # Wait for MinIO to be ready
          echo "Waiting for MinIO to start..."
          for i in {1..30}; do
            if curl -f http://localhost:9000/minio/health/live >/dev/null 2>&1; then
              echo "MinIO is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 3
          done

          # Verify MinIO is accessible
          echo "Testing MinIO accessibility..."
          curl -v http://localhost:9000/minio/health/live || {
            echo "MinIO health check failed!"
            docker logs minio
            exit 1
          }

      - name: Test Action - Latest Version
        uses: ./
        with:
          alias: testminio
          url: http://localhost:9000
          access_key: minioadmin
          secret_key: minioadmin
          bucket: test-bucket

      - name: Verify mc is in PATH
        run: |
          which mc
          mc --version

      - name: Test MinIO operations
        run: |
          # List buckets
          mc ls testminio

          # Create a test file
          echo "Hello MinIO!" > test.txt

          # Upload file
          mc cp test.txt testminio/test-bucket/

          # List bucket contents
          mc ls testminio/test-bucket

          # Download file
          mc cp testminio/test-bucket/test.txt downloaded.txt

          # Verify content
          cat downloaded.txt

          # Clean up
          mc rm testminio/test-bucket/test.txt

      - name: Test Action - Specific Version
        uses: ./
        with:
          alias: testminio2
          url: http://localhost:9000
          access_key: minioadmin
          secret_key: minioadmin
          version: "RELEASE.2024-01-16T16-06-34Z"
          verify_checksum: false

      - name: Test specific version works
        run: |
          mc --version
          mc ls testminio2

      - name: Cleanup MinIO
        if: always()
        run: |
          docker stop minio || true
          docker rm minio || true
